apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization    # 묶어서 관리하기 
namespace: monitoring-namespace
resources:
  - monitoring-service/deployment.yaml
  - monitoring-service/service.yaml
  - monitoring-service/ingress.yaml
  - namespace.yaml
