apiVersion: v1
kind: Service
metadata:
  name: monitoring-service
  namespace: monitoring-namespace
spec:
  selector:
    app: monitoring-service  # 이 파드랑 연결 
  ports:
    - protocol: TCP 
      port: 83  # 외부 포트 
      targetPort: 8080  # 내부 포트 
  type: ClusterIP  # 내부 연결만 -> 인그레스 사용할거니까 
